name: Student Reminder Notification

on:
  schedule:
    - cron: '*/500 * * * *'  # запуск каждые 5 минут (при необходимости измените на нужное расписание)
  workflow_dispatch:

jobs:
  notify_student:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run student_reminder script
        env:
          SIB_API_KEY: ${{ secrets.SIB_API_KEY }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node student_reminder.js
